services:
  signal-cli-rest-api:
    image: docker.io/bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=json-rpc #supported modes: json-rpc, native, normal
    ports:
      - "18080:8080"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli"

  bot:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    volumes:
      - "./config.yml:/app/config.yml:ro"
    depends_on:
      - signal-cli-rest-api
